# Generated by Django 5.1.1 on 2025-03-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0006_alter_mangapage_options'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_img',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_img_front',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='Manga.manga'),
        ),
        migrations.AddField(
            model_name='user',
            name='img_frame',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_img',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
