# Generated by Django 5.1.1 on 2025-03-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=155)),
                ('country_banner', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='MangaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='manga_pages/')),
                ('page_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=55, unique=True)),
                ('description_short', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('manga_name', models.CharField(max_length=255, unique=True)),
                ('manga_title', models.TextField()),
                ('manga_img', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('date_join', models.DateField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('manga_status', models.CharField(choices=[('выпускается', 'выпускается'), ('работа приостановлена', 'работа приостановлена'), ('Заброшенна', 'Заброшенна')], max_length=155)),
                ('translation_status', models.CharField(choices=[('перевод идет', 'перевод идет'), ('перевод приостановлен', 'перевод приостановлен'), ('Заброшенна', 'Заброшенна')], max_length=155)),
                ('manga_type', models.CharField(choices=[('манга', 'манга'), ('манхва', 'манхва'), ('маньхуа', 'маньхуа'), ('руманга', 'руманга')], max_length=50)),
                ('note', models.CharField(default='отсутствует', max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(default='неизвестно', on_delete=django.db.models.deletion.SET_DEFAULT, to='Manga.country')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('writer_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writer', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='Manga.tags')),
            ],
        ),
        migrations.CreateModel(
            name='MangaVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='manga_volumes/')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='Manga.manga')),
            ],
            options={
                'ordering': ['volume_number'],
            },
        ),
        migrations.CreateModel(
            name='MangaChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_title', models.CharField(max_length=155)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('chapter_number', models.IntegerField(default=0)),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='Manga.manga')),
                ('pages', models.ManyToManyField(related_name='chapter_pages', to='Manga.mangapage')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='Manga.mangavolume')),
            ],
            options={
                'ordering': ['volume', 'chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='MangaView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_log', to='Manga.manga')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'manga')},
            },
        ),
    ]
