# Generated by Django 5.1.1 on 2025-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0004_alter_comment_options_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangachapters',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='chapter_pages', to='Manga.mangapage'),
        ),
    ]
