# Generated by Django 5.1.1 on 2025-03-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0005_alter_mangachapters_pages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangapage',
            options={'ordering': ['page_number']},
        ),
    ]
