# Generated by Django 5.1.1 on 2025-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0006_alter_mangapage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='note',
            field=models.CharField(default='отсутствует', max_length=600),
        ),
    ]
