# Generated by Django 5.1.1 on 2025-05-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manga', '0007_alter_manga_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['-date_join']},
        ),
        migrations.AlterField(
            model_name='manga',
            name='note',
            field=models.TextField(default='отсутствует'),
        ),
    ]
