from django.urls import path
from .views import *

urlpatterns = [
    path("", Manga_chapters_API.as_view()),
    path("user_show", User_show.as_view()),
    path("country", Country_show_API.as_view()),
    path("country/<int:pk>", Country_one_show_API.as_view()),
    path("manga/<slug:slug>/<int:chapter_number>/", MangaChapterDetailView.as_view()),
    path("manga/<int:pageID>/comments", MangaPageCommentView.as_view()),
    path("manga/<slug:slug>", One_Manga_API.as_view()),
    path("manga/profile/<slug:slug>", ProfileMangaView.as_view()),
    path("manga/<slug:slug>/chapters/", MangaChapterListView.as_view()),
    path("manga_profile/<slug:slug>/chapters/", MangaProfileChapterListView.as_view()),
    path("manga/<slug:slug>/volumes/", MangaVolumeListCreateView.as_view(), name='manga-volume-list-create'),
    path('manga/chapters/<int:pk>/like/', MangaChapterLikeAPIView.as_view()),
    path("manga/add/", OneMangaAddAPI.as_view()),
    path("manga/<slug:slug>/update/", MangaUpdateAPI.as_view()),
    path("tags_list",Tags_API.as_view()),
    path("<int:pk>", One_Manga_API.as_view()),
    path('<int:pk>/like/', AddLike.as_view()),
    path('<int:pk>/dislike/', AddDislike.as_view()),
    path("user_manga",User_manga.as_view()),
    path("manga/<slug:slug>/chapter_add/",Manga_chapter_add.as_view()),
    path('manga/<slug:slug>/chapter_update/<int:chapter_number>', Manga_chapter_update.as_view()),
    path("manga/chapter/<int:chapter_id>/add_page", AddPageToChapterView.as_view()),
    path("manga/chapter/<int:chapter_id>/pages", UpdatePageInChapterView.as_view()),
    path("last_chapter/<int:pk>",Manga_last_chapter.as_view()),
    path('manga/<slug:slug>/volumes/<int:pk>/', MangaVolumeDetailView.as_view(), name='manga-volume-detail'),
    path('manga/<slug:slug>/chapter_delete/<int:chapter_number>', MangaChapterDeleteView.as_view()),
]
